version: '3.1'

services:
  libraree-app:
    build: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - libraree-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/libraree?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=libraree
    depends_on:
      - db

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: libraree
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - libraree-net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - libraree-net

volumes:
  db_data:

networks:
  libraree-net: