version: '3.1'

services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: libraree
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - libraree-net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - libraree-net

volumes:
  db_data:

networks:
  libraree-net: