version: '3.1'

services:

  libraree-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - spring.datasource.url=jdbc:mysql://localhost:3306/libraree
      - spring.datasource.username=root
      - spring.datasource.password=libraree
      - flyway.url=jdbc:mysql://localhost:3306/libraree
      - flyway.user=root
      - flyway.password=libraree
    depends_on:
      - db

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: libraree
    ports:
      - 3306:3306
#        server: libraree-db-1
#        username: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3307:80
#    environment:
#      - PMA_ARBITRARY=1